---
title: "week5 Discussion"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
# Load packages
library(tidyverse)
library(sf)
library(terra)
library(spData)
library(spDataLarge)
```

```{r}
# Load raster data representing grain sizes with the three classes clay, silt and sand
grain <- terra::rast(system.file("raster/grain.tif", package = "spData"))
```


## 3.1
### Subset points higher than 3100 meters in `nz_height`
```{r}
# Filter NZ data to only elevations higher than 3100
nz_height_3100 <- nz_height %>%
  filter(elevation > 3100)

# Create template: define the extent, resolution, and CRS based on nz_height3100
nz_template <- rast(terra::ext(nz_height_3100), 
                    resolution = 3000, 
                    crs = terra::crs(nz_height_3100))

```


### Count numbers of the highest points in each grid cell
```{r}
# Convert vecotr points to raster data
# Function "length" returns a count of the elevation points per cell
nz_raster <- rasterize(nz_height_3100, nz_template, field = "elevation", fun = "length")

plot(nz_raster, main = "Number of Elevation Points > 3100 in Each Grid Cell")
plot(st_geometry(nz_height_3100), add = TRUE)
```


### Find the maximum elevation in each grid cell
```{r}
# Function "max" returns maximum elevation value per cell
nz_raster2 <- rasterize(nz_height_3100, nz_template, field = "elevation", fun = max)

plot(nz_raster2, main = "Maximum Elevation in Each Grid Cell")
plot(st_geometry(nz_height_3100), add = TRUE)

```

## 3.2 
### With the previous raster, complete the following:

### Aggregate the raster that counts the highest points in New Zealand/Aotearoa
```{r}
# Reduce the resolution by combining 2 cells in each direction into larger cells
# Sum the values of all cells for the resulting elevation value
nz_raster_low <- aggregate(nz_raster, fact = 2, fun = sum, na.rm = TRUE)

# Convert the new raster's resolution back to the 3km x 3km resolution of original raster
nz_resample <- resample(nz_raster_low, nz_raster)

plots <- c(nz_raster, nz_resample)
labs <- c("Original 6 x 6 km", "Resample 6 x 6 km")
plot(plots, main = labs)
```


